AZURE_LOCATION: 'westeurope'
RESOURCE_NAME_PREFIX: 'solais'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'solais-ase-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'https://dev.azure.com/SveaSolar/'
CICD_AGENT_TYPE: 'azuredevops'
CERT_TYPE: 'selfsigned'
